In [3]:
from bs4 import BeautifulSoup
import requests
import re 
import pandas as pd

In [3]:
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

IMDB WEB SCRAPER

In [4]:
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value') for b in soup.select('td.posterColumn span[name=ir]')]

In [5]:
list = []

for i in range(0, len(movies)):
  movie_string = movies[i].get_text()
  movie = (' '.join(movie_string.split()).replace('.',''))
  movie_title = movie[len(str(i))+1:-7]
  year = re.search('\((.*?)\)', movie_string).group(1)
  place = movie[:len(str(i))-(len(movie))]
  data = {"place": place,
          "movie_title": movie_title,
          "rating": ratings[i],
          "year": year,
          "star_cast": crew[i],
          }
  list.append(data)

In [6]:
for movie in list:
    print(movie['place'], '-', movie['movie_title'], '('+movie['year'] +
        ') -', 'Starring:', movie['star_cast'], movie['rating'])

1 - The Shawshank Redemption (1994) - Starring: Frank Darabont (dir.), Tim Robbins, Morgan Freeman 9.235230166300775
2 - The Godfather (1972) - Starring: Francis Ford Coppola (dir.), Marlon Brando, Al Pacino 9.156061424490264
3 - The Dark Knight (2008) - Starring: Christopher Nolan (dir.), Christian Bale, Heath Ledger 8.989229562795877
4 - The Godfather Part II (1974) - Starring: Francis Ford Coppola (dir.), Al Pacino, Robert De Niro 8.984062576502275
5 - De 12 gezworenen (1957) - Starring: Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb 8.950831392553201
6 - Schindler's List (1993) - Starring: Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes 8.937939794664905
7 - The Lord of the Rings: The Return of the King (2003) - Starring: Peter Jackson (dir.), Elijah Wood, Viggo Mortensen 8.92851615029403
8 - Pulp Fiction (1994) - Starring: Quentin Tarantino (dir.), John Travolta, Uma Thurman 8.848454480539717
9 - The Lord of the Rings: The Fellowship of the Ring (2001) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.808615575049544
1 -  The Good, the Bad and the Ugly (1966) - Starring: Sergio Leone (dir.), Clint Eastwood, Eli Wallach 8.791131910995965
11 - Forrest Gump (1994) - Starring: Robert Zemeckis (dir.), Tom Hanks, Robin Wright 8.767688617725817
12 - Fight Club (1999) - Starring: David Fincher (dir.), Brad Pitt, Edward Norton 8.748783940753817
13 - The Lord of the Rings: The Two Towers (2002) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.733771379599602
14 - Inception (2010) - Starring: Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt 8.73329648802952
15 - Star Wars: Episode V - The Empire Strikes Back (1980) - Starring: Irvin Kershner (dir.), Mark Hamill, Harrison Ford 8.700063665987496
16 - The Matrix (1999) - Starring: Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne 8.669950543484752
17 - Goodfellas (1990) - Starring: Martin Scorsese (dir.), Robert De Niro, Ray Liotta 8.65231219510955
18 - One Flew Over the Cuckoo's Nest (1975) - Starring: Milos Forman (dir.), Jack Nicholson, Louise Fletcher 8.639532336986154
19 - Seven (1995) - Starring: David Fincher (dir.), Morgan Freeman, Brad Pitt 8.604333187335678
20 - Shichinin no samurai (1954) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura 8.599315819544644
21 - It's a Wonderful Life (1946) - Starring: Frank Capra (dir.), James Stewart, Donna Reed 8.5957938284675
22 - The Silence of the Lambs (1991) - Starring: Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins 8.588191887909765
23 - Cidade de Deus (2002) - Starring: Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino 8.579683606927237
24 - Saving Private Ryan (1998) - Starring: Steven Spielberg (dir.), Tom Hanks, Matt Damon 8.578955253453685
25 - Het leven is mooi (1997) - Starring: Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi 8.568105500679742
26 - Interstellar (2014) - Starring: Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway 8.56386594527459
27 - The Green Mile (1999) - Starring: Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan 8.562076557849831
28 - De sterrenoorlogen (1977) - Starring: George Lucas (dir.), Mark Hamill, Harrison Ford 8.55067510972777
29 - Terminator 2: Judgment Day (1991) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton 8.536241607982562
30 - Terug naar de toekomst (1985) - Starring: Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd 8.517923167622214
31 - Spirited Away (2001) - Starring: Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette 8.516253737451542
32 - Psycho (1960) - Starring: Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh 8.507561044466046
33 - The Pianist (2002) - Starring: Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann 8.506357740414918
34 - Gisaengchung (2019) - Starring: Bong Joon Ho (dir.), Song Kang-ho, Lee Sun-kyun 8.497830153169092
35 - Léon (1994) - Starring: Luc Besson (dir.), Jean Reno, Gary Oldman 8.496567531719792
36 - The Lion King (1994) - Starring: Roger Allers (dir.), Matthew Broderick, Jeremy Irons 8.488358107234433
37 - Gladiator (2000) - Starring: Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix 8.486374653467298
38 - American History X (1998) - Starring: Tony Kaye (dir.), Edward Norton, Edward Furlong 8.482971345150293
39 - The Departed (2006) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon 8.475651118185853
40 - The Usual Suspects (1995) - Starring: Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne 8.472513011012937
41 - The Prestige (2006) - Starring: Christopher Nolan (dir.), Christian Bale, Hugh Jackman 8.468866347635126
42 - Whiplash (2014) - Starring: Damien Chazelle (dir.), Miles Teller, J.K. Simmons 8.464686805825453
43 - Casablanca (1942) - Starring: Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman 8.463314170953858
44 - Seppuku (1962) - Starring: Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama 8.454516103661657
45 - Intouchables (2011) - Starring: Olivier Nakache (dir.), François Cluzet, Omar Sy 8.45432631505875
46 - Grave of the Fireflies (1988) - Starring: Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi 8.453574422721166
47 - Modern Times (1936) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.448792057146907
48 - Once Upon a Time in the West (1968) - Starring: Sergio Leone (dir.), Henry Fonda, Charles Bronson 8.444765608302928
49 - Rear Window (1954) - Starring: Alfred Hitchcock (dir.), James Stewart, Grace Kelly 8.436111041423256
50 - Alien (1979) - Starring: Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt 8.43404047989176
51 - City Lights (1931) - Starring: Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill 8.433821449144787
52 - Cinema Paradiso (1988) - Starring: Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale 8.433716099853594
53 - Apocalypse Now (1979) - Starring: Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando 8.424088143888728
54 - Memento (2000) - Starring: Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss 8.422705904219564
55 - Indiana Jones and the Raiders of the Lost Ark (1981) - Starring: Steven Spielberg (dir.), Harrison Ford, Karen Allen 8.408663825323629
56 - Django Unchained (2012) - Starring: Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz 8.406377125863058
57 - WALL-E (2008) - Starring: Andrew Stanton (dir.), Ben Burtt, Elissa Knight 8.394242831877573
58 - Das Leben der Anderen (2006) - Starring: Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck 8.385262597327392
59 - Sunset Boulevard (1950) - Starring: Billy Wilder (dir.), William Holden, Gloria Swanson 8.380070141512245
60 - Het veld van eer (1957) - Starring: Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker 8.371963440404766
61 - De dictator (1940) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.365845883665031
62 - The Shining (1980) - Starring: Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall 8.36579610555303
63 - Avengers: Infinity War (2018) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth 8.360614151573824
64 - Witness for the Prosecution (1957) - Starring: Billy Wilder (dir.), Tyrone Power, Marlene Dietrich 8.360047884992474
65 - Aliens (1986) - Starring: James Cameron (dir.), Sigourney Weaver, Michael Biehn 8.34312721213006
66 - Spider-Man: Een nieuw universum (2018) - Starring: Bob Persichetti (dir.), Shameik Moore, Jake Johnson 8.334066545928069
67 - American Beauty (1999) - Starring: Sam Mendes (dir.), Kevin Spacey, Annette Bening 8.333717721597251
68 - Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - Starring: Stanley Kubrick (dir.), Peter Sellers, George C. Scott 8.330028090756729
69 - The Dark Knight Rises (2012) - Starring: Christopher Nolan (dir.), Christian Bale, Tom Hardy 8.327387087079183
70 - Oldboy (2003) - Starring: Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-tae 8.320530505393908
71 - Joker (2019) - Starring: Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro 8.316101376512924
72 - Amadeus (1984) - Starring: Milos Forman (dir.), F. Murray Abraham, Tom Hulce 8.315950598796903
73 - Inglourious Basterds (2009) - Starring: Quentin Tarantino (dir.), Brad Pitt, Diane Kruger 8.315087401487892
74 - Coco (2017) - Starring: Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal 8.314672122526286
75 - Toy Story (1995) - Starring: John Lasseter (dir.), Tom Hanks, Tim Allen 8.314249947317132
76 - Braveheart (1995) - Starring: Mel Gibson (dir.), Mel Gibson, Sophie Marceau 8.313894183511454
77 - Das Boot (1981) - Starring: Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer 8.312372894756743
78 - Avengers: Endgame (2019) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Evans 8.304354267324333
79 - Princess Mononoke (1997) - Starring: Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida 8.303386355433522
80 - Once Upon a Time in America (1984) - Starring: Sergio Leone (dir.), Robert De Niro, James Woods 8.296652348472461
81 - Top Gun: Maverick (2022) - Starring: Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly 8.289444598225419
82 - Good Will Hunting (1997) - Starring: Gus Van Sant (dir.), Robin Williams, Matt Damon 8.28916689123661
83 - Your Name (2016) - Starring: Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi 8.280139092446323
84 - Requiem for a Dream (2000) - Starring: Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto 8.275581483414824
85 - Singin' in the Rain (1952) - Starring: Stanley Donen (dir.), Gene Kelly, Donald O'Connor 8.273696817907704
86 - Toy Story 3 (2010) - Starring: Lee Unkrich (dir.), Tom Hanks, Tim Allen 8.273667679828199
87 - 3 Idiots (2009) - Starring: Rajkumar Hirani (dir.), Aamir Khan, Madhavan 8.273617011411107
88 - Tengoku to jigoku (1963) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada 8.270730709810334
89 - Star Wars: Episode VI - Return of the Jedi (1983) - Starring: Richard Marquand (dir.), Mark Hamill, Harrison Ford 8.26561447634586
90 - Capernaum (2018) - Starring: Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw 8.26319557656111
91 - Eternal Sunshine of the Spotless Mind (2004) - Starring: Michel Gondry (dir.), Jim Carrey, Kate Winslet 8.262838200561562
92 - 2001: Een zwerftocht in de ruimte (1968) - Starring: Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood 8.262755621060373
93 - Reservoir Dogs (1992) - Starring: Quentin Tarantino (dir.), Harvey Keitel, Tim Roth 8.261629322784298
94 - The Hunt (2012) - Starring: Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen 8.256187622374817
95 - Idi i smotri (1985) - Starring: Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova 8.253340738136334
96 - Citizen Kane (1941) - Starring: Orson Welles (dir.), Orson Welles, Joseph Cotten 8.25332508766241
97 - M - Eine Stadt sucht einen Mörder (1931) - Starring: Fritz Lang (dir.), Peter Lorre, Ellen Widmann 8.25232091081684
98 - Lawrence of Arabia (1962) - Starring: David Lean (dir.), Peter O'Toole, Alec Guinness 8.252134841559883
99 - North by Northwest (1959) - Starring: Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint 8.248150181198342
10 -  Vertigo (1958) - Starring: Alfred Hitchcock (dir.), James Stewart, Kim Novak 8.244636649071786
101 - Le fabuleux destin d'Amélie Poulain (2001) - Starring: Jean-Pierre Jeunet (dir.), Audrey Tautou, Mathieu Kassovitz 8.243905949552662
102 - A Clockwork Orange (1971) - Starring: Stanley Kubrick (dir.), Malcolm McDowell, Patrick Magee 8.241558036095165
103 - Het appartement (1960) - Starring: Billy Wilder (dir.), Jack Lemmon, Shirley MacLaine 8.239676567887475
104 - Ikiru (1952) - Starring: Akira Kurosawa (dir.), Takashi Shimura, Nobuo Kaneko 8.238705078459716
105 - Bloedgeld (1944) - Starring: Billy Wilder (dir.), Fred MacMurray, Barbara Stanwyck 8.23864678699356
106 - Full Metal Jacket (1987) - Starring: Stanley Kubrick (dir.), Matthew Modine, R. Lee Ermey 8.238137387443388
107 - Hamilton (2020) - Starring: Thomas Kail (dir.), Lin-Manuel Miranda, Phillipa Soo 8.23517290567315
108 - Scarface (1983) - Starring: Brian De Palma (dir.), Al Pacino, Michelle Pfeiffer 8.23501131145736
109 - The Sting (1973) - Starring: George Roy Hill (dir.), Paul Newman, Robert Redford 8.227557542215843
110 - To Kill a Mockingbird (1962) - Starring: Robert Mulligan (dir.), Gregory Peck, John Megna 8.226906470947926
111 - Incendies (2010) - Starring: Denis Villeneuve (dir.), Lubna Azabal, Mélissa Désormeaux-Poulin 8.224749386531114
112 - Up (2009) - Starring: Pete Docter (dir.), Edward Asner, Jordan Nagai 8.224555156096484
113 - Heat (1995) - Starring: Michael Mann (dir.), Al Pacino, Robert De Niro 8.224378040125183
114 - Taxi Driver (1976) - Starring: Martin Scorsese (dir.), Robert De Niro, Jodie Foster 8.223014390222927
115 - A Separation (2011) - Starring: Asghar Farhadi (dir.), Payman Maadi, Leila Hatami 8.222076510139507
116 - Metropolis (1927) - Starring: Fritz Lang (dir.), Brigitte Helm, Alfred Abel 8.221546096750355
117 - LA Confidential (1997) - Starring: Curtis Hanson (dir.), Kevin Spacey, Russell Crowe 8.22096137896028
118 - Snatch (2000) - Starring: Guy Ritchie (dir.), Jason Statham, Brad Pitt 8.2184114918727
119 - Die Hard (1988) - Starring: John McTiernan (dir.), Bruce Willis, Alan Rickman 8.218097703493887
120 - Ladri di biciclette (1948) - Starring: Vittorio De Sica (dir.), Lamberto Maggiorani, Enzo Staiola 8.217426335911448
121 - Indiana Jones and the Last Crusade (1989) - Starring: Steven Spielberg (dir.), Harrison Ford, Sean Connery 8.217003448109114
122 - Taare Zameen Par (2007) - Starring: Aamir Khan (dir.), Darsheel Safary, Aamir Khan 8.211755886487076
123 - 1917 (2019) - Starring: Sam Mendes (dir.), Dean-Charles Chapman, George MacKay 8.211592756685056
124 - Der Untergang (2004) - Starring: Oliver Hirschbiegel (dir.), Bruno Ganz, Alexandra Maria Lara 8.203758166235827
125 - For a Few Dollars More (1965) - Starring: Sergio Leone (dir.), Clint Eastwood, Lee Van Cleef 8.20111394815259
126 - Dangal (2016) - Starring: Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar 8.199610477986106
127 - Batman Begins (2005) - Starring: Christopher Nolan (dir.), Christian Bale, Michael Caine 8.199397422249536
128 - The Kid (1921) - Starring: Charles Chaplin (dir.), Charles Chaplin, Edna Purviance 8.192890284446376
129 - Some Like It Hot (1959) - Starring: Billy Wilder (dir.), Marilyn Monroe, Tony Curtis 8.191401685403246
130 - The Father (2020) - Starring: Florian Zeller (dir.), Anthony Hopkins, Olivia Colman 8.181108958571013
131 - All About Eve (1950) - Starring: Joseph L. Mankiewicz (dir.), Bette Davis, Anne Baxter 8.18068185694055
132 - Green Book (2018) - Starring: Peter Farrelly (dir.), Viggo Mortensen, Mahershala Ali 8.176444767710944
133 - The Wolf of Wall Street (2013) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Jonah Hill 8.175153550860413
134 - Oordeel te Neurenberg (1961) - Starring: Stanley Kramer (dir.), Spencer Tracy, Burt Lancaster 8.170105608315053
135 - Ran (1985) - Starring: Akira Kurosawa (dir.), Tatsuya Nakadai, Akira Terao 8.164669520059743
136 - Casino (1995) - Starring: Martin Scorsese (dir.), Robert De Niro, Sharon Stone 8.164034355992436
137 - Pan's Labyrinth (2006) - Starring: Guillermo del Toro (dir.), Ivana Baquero, Ariadna Gil 8.1620180196684
138 - Unforgiven (1992) - Starring: Clint Eastwood (dir.), Clint Eastwood, Gene Hackman 8.16069730897483
139 - There Will Be Blood (2007) - Starring: Paul Thomas Anderson (dir.), Daniel Day-Lewis, Paul Dano 8.157739000362866
140 - The Truman Show (1998) - Starring: Peter Weir (dir.), Jim Carrey, Ed Harris 8.156834600833026
141 - The Sixth Sense (1999) - Starring: M. Night Shyamalan (dir.), Bruce Willis, Haley Joel Osment 8.153708307917077
142 - A Beautiful Mind (2001) - Starring: Ron Howard (dir.), Russell Crowe, Ed Harris 8.151789938855073
143 - Spider-Man: No Way Home (2021) - Starring: Jon Watts (dir.), Tom Holland, Zendaya 8.15092322138486
144 - Yôjinbô (1961) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Eijirô Tôno 8.149378704500764
145 - Shutter Island (2010) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Emily Mortimer 8.14901299721088
146 - Monty Python and the Holy Grail (1975) - Starring: Terry Gilliam (dir.), Graham Chapman, John Cleese 8.14898556555663
147 - The Treasure of the Sierra Madre (1948) - Starring: John Huston (dir.), Humphrey Bogart, Walter Huston 8.147732221592667
148 - Jurassic Park (1993) - Starring: Steven Spielberg (dir.), Sam Neill, Laura Dern 8.146374577504629
149 - Rashômon (1950) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Machiko Kyô 8.141307075731527
150 - The Great Escape (1963) - Starring: John Sturges (dir.), Steve McQueen, James Garner 8.141253181180797
151 - Kill Bill (2003) - Starring: Quentin Tarantino (dir.), Uma Thurman, David Carradine 8.137943654572705
152 - No Country for Old Men (2007) - Starring: Ethan Coen (dir.), Tommy Lee Jones, Javier Bardem 8.137616748625195
153 - Finding Nemo (2003) - Starring: Andrew Stanton (dir.), Albert Brooks, Ellen DeGeneres 8.131605856302963
154 - The Thing (1982) - Starring: John Carpenter (dir.), Kurt Russell, Wilford Brimley 8.130725554998605
155 - The Elephant Man (1980) - Starring: David Lynch (dir.), Anthony Hopkins, John Hurt 8.128584296144929
156 - Chinatown (1974) - Starring: Roman Polanski (dir.), Jack Nicholson, Faye Dunaway 8.127514826734867
157 - Raging Bull (1980) - Starring: Martin Scorsese (dir.), Robert De Niro, Cathy Moriarty 8.12589799919695
158 - V for Vendetta (2005) - Starring: James McTeigue (dir.), Hugo Weaving, Natalie Portman 8.124225244002744
159 - Gejaagd door de wind (1939) - Starring: Victor Fleming (dir.), Clark Gable, Vivien Leigh 8.123970738733004
160 - Binnenstebuiten (2015) - Starring: Pete Docter (dir.), Amy Poehler, Bill Hader 8.12224916221497
161 - Lock, Stock and Two Smoking Barrels (1998) - Starring: Guy Ritchie (dir.), Jason Flemyng, Dexter Fletcher 8.121658207043062
162 - Dial M for Murder (1954) - Starring: Alfred Hitchcock (dir.), Ray Milland, Grace Kelly 8.119701815525497
163 - El secreto de sus ojos (2009) - Starring: Juan José Campanella (dir.), Ricardo Darín, Soledad Villamil 8.117605042445899
164 - Howl's Moving Castle (2004) - Starring: Hayao Miyazaki (dir.), Chieko Baishô, Takuya Kimura 8.116130697455604
165 - The Bridge on the River Kwai (1957) - Starring: David Lean (dir.), William Holden, Alec Guinness 8.11236869611017
166 - Three Billboards Outside Ebbing, Missouri (2017) - Starring: Martin McDonagh (dir.), Frances McDormand, Woody Harrelson 8.111521428972852
167 - Trainspotting (1996) - Starring: Danny Boyle (dir.), Ewan McGregor, Ewen Bremner 8.111035874917416
168 - Warrior (2011) - Starring: Gavin O'Connor (dir.), Tom Hardy, Nick Nolte 8.103457519197487
169 - Gran Torino (2008) - Starring: Clint Eastwood (dir.), Clint Eastwood, Bee Vang 8.102403758058532
170 - Fargo (1996) - Starring: Joel Coen (dir.), William H. Macy, Frances McDormand 8.102327622765488
171 - Prisoners (2013) - Starring: Denis Villeneuve (dir.), Hugh Jackman, Jake Gyllenhaal 8.100946695813088
172 - My Neighbor Totoro (1988) - Starring: Hayao Miyazaki (dir.), Hitoshi Takagi, Noriko Hidaka 8.093981748975752
173 - Million Dollar Baby (2004) - Starring: Clint Eastwood (dir.), Hilary Swank, Clint Eastwood 8.089226699569476
174 - Catch Me If You Can (2002) - Starring: Steven Spielberg (dir.), Leonardo DiCaprio, Tom Hanks 8.089008379072125
175 - Bacheha-Ye aseman (1997) - Starring: Majid Majidi (dir.), Mohammad Amir Naji, Amir Farrokh Hashemian 8.086066262191968
176 - The Gold Rush (1925) - Starring: Charles Chaplin (dir.), Charles Chaplin, Mack Swain 8.085272926411033
177 - Blade Runner (1982) - Starring: Ridley Scott (dir.), Harrison Ford, Rutger Hauer 8.084827276324459
178 - On the Waterfront (1954) - Starring: Elia Kazan (dir.), Marlon Brando, Karl Malden 8.081688809943028
179 - Before Sunrise (1995) - Starring: Richard Linklater (dir.), Ethan Hawke, Julie Delpy 8.080511821582117

In [7]:
df = pd.DataFrame(list)
df.to_csv('imdb_top_250_movies.csv',index=False)

In [8]:
df.head(10)

,place,movie_title,rating,year,star_cast
0,1,The Shawshank Redemption,9.235230166300775,1994,"Frank Darabont (dir.), Tim Robbins, Morgan Fre..."
1,2,The Godfather,9.156061424490264,1972,"Francis Ford Coppola (dir.), Marlon Brando, Al..."
2,3,The Dark Knight,8.989229562795877,2008,"Christopher Nolan (dir.), Christian Bale, Heat..."
3,4,The Godfather Part II,8.984062576502275,1974,"Francis Ford Coppola (dir.), Al Pacino, Robert..."
4,5,De 12 gezworenen,8.950831392553201,1957,"Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb"
5,6,Schindler's List,8.937939794664905,1993,"Steven Spielberg (dir.), Liam Neeson, Ralph Fi..."
6,7,The Lord of the Rings: The Return of the King,8.92851615029403,2003,"Peter Jackson (dir.), Elijah Wood, Viggo Morte..."
7,8,Pulp Fiction,8.848454480539717,1994,"Quentin Tarantino (dir.), John Travolta, Uma T..."
8,9,The Lord of the Rings: The Fellowship of the Ring,8.808615575049544,2001,"Peter Jackson (dir.), Elijah Wood, Ian McKellen"
9,1,"The Good, the Bad and the Ugly",8.791131910995965,1966,"Sergio Leone (dir.), Clint Eastwood, Eli Wallach"

AMAZON WEB SCRAPER

In [86]:
import smtplib
import datetime

In [87]:
# Connect to website

In [88]:
url = 'https://www.amazon.co.uk/Faber-Castell-Grip-2011-Finewriter-Pen/dp/B07QBB8ZQC/?_encoding=UTF8&pd_rd_w=glPJv&content-id=amzn1.sym.a71261a5-450a-406b-a560-7052648aeb75&pf_rd_p=a71261a5-450a-406b-a560-7052648aeb75&pf_rd_r=2C1GXX8B8PYRSTVRYM09&pd_rd_wg=duvZh&pd_rd_r=5bcdb691-92d3-4984-9663-4576603c53c4&ref_=pd_gw_ci_mcx_mr_hp_d'
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"}
page = requests.get(url, headers = headers)
soup1 = BeautifulSoup(page.content, 'html.parser')
soup2 = BeautifulSoup(soup1.prettify(),'html.parser')

title = soup2.find(id='productTitle').get_text()
num_ratings = soup2.find(id='acrCustomerReviewText').get_text()

print(title)
print(num_ratings)

            Faber-Castell Grip 2011 Finewriter Pen - Black


             231 ratings

In [89]:
num_ratings = num_ratings.split()
num_ratings = num_ratings[0]
title = title.strip()
today = datetime.date.today()

In [90]:
import csv
header = ['title', 'num_rating','date']
df = [title, num_ratings, today]
with open('web_screper2.csv','w', newline = '', encoding = 'UTF8') as f:
  writer = csv.writer(f)
  writer.writerow(header)
  writer.writerow(df)

In [91]:
import pandas as pd 
new_df = pd.read_csv('web_screper2.csv')

In [92]:
new_df.head(1)

                                            title  num_rating        date
0  Faber-Castell Grip 2011 Finewriter Pen - Black         231  2022-11-21